### ISSUE TITLE
How to style a button to have alpha or scale value when user press

### ISSUE THREAD

**Issue by takaaptech** [ex-makina-b/marklight#7]
Hi,
I just found it is awesome GUI lib for unity! I try to make custom theme for button with single image for both state: normal and pressed, and i want when user pressed, image change alpha value (or scale to 1.1):
```
<Button Id="home" BackgroundImage="Sprites/640_18.png" Width="102" Height="102"/>
```
How can i get it? Thank so much! 

P/S It is very easy to define Pressed-BackgroundImage with new alpha value or scale value but i think we should support alpha or scale directly on BackgroundImage for better size and performance!

**Comment by ex-makina** [comment]
Hi

As you suggested you can set `Pressed-Alpha="..."` and `Pressed-Scale="..."` on the button. If you want to change fields on the image component that the Button (UIView) doesn't provide mapped fields to, then you can access them through ImageComponent field. E.g:

    <Button ImageComponent.color="#000000" />

**Comment by takaaptech** [comment]
Awesome! I just test and it works as expected! Thank you so much!
So i assume that our document and our api are not up to date..
